name: CI
permissions:
  contents: read

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build Docker image
      uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # v1.1.2
      with:
        repository: matplotlib/mpl-docker
        dockerfile: Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List built images
      run: docker images
